# Generated by Django 5.0.7 on 2024-08-05 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='order',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='timestamp',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='update_desc',
            field=models.CharField(default='order has been placed', max_length=5000),
        ),
    ]
