# Generated by Django 5.0.7 on 2024-08-05 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_alter_tracker_order_alter_tracker_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.checkout'),
        ),
    ]
