# Generated by Django 5.0.7 on 2024-08-05 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_alter_tracker_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='amount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
