# Generated by Django 5.0.7 on 2024-08-05 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0004_checkout_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
